dependencies {
    implementation project(':core')
    implementation project(':ext-udpqueue')
    implementation group: 'com.mewna', name: 'catnip', version: '1.3.3'
    implementation group: 'com.sedmelluq', name: 'lavaplayer', version: '1.3.48'
    implementation group: 'ch.qos.logback', name: 'logback-classic', version: '1.3.0-alpha4'
}
